stella-cv/stella_vslam

- .gitignore
- CMakePresets.json
- scripts/windows/Build.bat
- scripts/windows/Setup.bat
- src/openvslam/CMakeLists.txt
+ Add build script
+ Added CONFIG flag to find_package SuiteSparse to find missing cs.h
+ Currently only static build is supported
Examples are disabled because Pangolin build fails with vcpkg
ref. #23
> CMake add presets for windows build

- .gitmodules
- CMakeLists.txt
- Dockerfile.desktop
- Dockerfile.ros
- Dockerfile.ros2
- Dockerfile.socket
- package.xml
- ros/1/src/openvslam/CMakeLists.txt
- ros/2/src/openvslam/CMakeLists.txt
- src/openvslam/CMakeLists.txt
- wercker.yml
I have confirmed that I can build with `colcon build` and `catkin_make_isolated`.
Since DBoW2 is licensed under BSD+notification, I used FBoW as a submodule.
> Build by colcon and catkin_make_isolated

- ros/2/src/openvslam/CMakeLists.txt
- ros/2/src/openvslam/src/CMakeLists.txt
- ros/2/src/openvslam/src/openvslam_ros.cc
- ros/2/src/openvslam/src/openvslam_ros.h
- ros/2/src/openvslam/src/run_slam.cc
- ros/2/src/publisher/src/video_publisher.cc
Hi. The changes are the following:
- adding the support for stereo input (ROS2)
- using ROS simulation time instead of system time
- printing msgs with RCLCPP_INFO instead of std::cout
- changing the publisher's topic to match with the subscriber's topic.
> Adding support for stereo input (ROS2)

- docs/parameters.rst
- src/openvslam/data/map_database.cc
- src/openvslam/data/map_database.h
- src/openvslam/module/relocalizer.cc
- src/openvslam/module/relocalizer.h
- src/openvslam/system.cc
- src/openvslam/system.h
- src/openvslam/tracking_module.cc
- src/openvslam/tracking_module.h
Adding new `system.h/system.cc` API call for updating camera position by known pose. This is a part required for https://github.com/OpenVSLAM-Community/openvslam_ros/issues/11 ticket to add the support of the `/initialpose` intentionally set by developer.
> Add update_pose() API call

- src/openvslam/system.cc
- src/openvslam/system.h
As, `system::feed_monocular/stereo/RGBD_frame()` return inverted WC-pose, it is logically that `update_pose(pose)` should also take the `pose_wc` in the same coordinate system as other main API routines.
> Change pose_cw to pose_wc in update_pose

- src/openvslam/CMakeLists.txt
- src/openvslam/data/common.cc
Fixed the remaining task in #3 
1. Fix warning by removing redundant std::move() 
2. Added double quotes around BUILD_INTERFACE and INSTALL_INTERFACE
> Merge bug Fixes

- src/openvslam/util/stereo_rectifier.cc
This PR fixes a faulty downcast that happens when enabling stereo rectification on a fisheye pair of cameras.
> Fix fisheye rectification downcast

- src/openvslam/util/stereo_rectifier.cc
This PR fixes the stereo rectification configuration loading, which is reading the configuration from the wrong YAML node (one level up from where it should).
> Fix stereo rectifier node loader

- src/openvslam/match/robust.cc
https://github.com/OpenVSLAM-Community/openvslam/issues/36
> reproject_to_bearing can return false indicating that the bearing is not valid and should not be used.  For example, perspective::reproject_to_bearing will return false and an invalid bearing if the depth is negative.  The resulting invalid bearing is not normalized, which can cause many potential landmarks to get thrown out in the epipole check.  This fix skips the epipole check if epiplane_in_keyfrm_2 is not valid
> perform epipole check only for valid bearing

- README.md
See https://github.com/OpenVSLAM-Community/openvslam/issues/37.
> Add Acknowledgements to README.md

- src/openvslam/data/graph_node.cc
- src/openvslam/data/keyframe.cc
- src/openvslam/data/map_database.cc
- src/openvslam/global_optimization_module.cc
- src/openvslam/io/map_database_io.cc
- src/openvslam/io/trajectory_io.cc
- src/openvslam/mapping_module.cc
- src/openvslam/module/local_map_cleaner.cc
- src/openvslam/module/loop_detector.cc
- src/openvslam/optimize/global_bundle_adjuster.cc
- src/openvslam/tracking_module.cc
Refactor some files appearing as a warning during clang compile, eg:
```
.../openvslam/src/openvslam/data/graph_node.cc:293:29: warning: loop variable 'parent_candidate' creates a copy from type 'const std::shared_ptr<openvslam::data::keyframe>' [-Wrange-loop-construct]
for (const auto parent_candidate : intersection) {
^
.../openvslam/src/openvslam/data/graph_node.cc:293:18: note: use reference type 'const std::shared_ptr<openvslam::data::keyframe> &' to prevent copying
for (const auto parent_candidate : intersection) {
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
> refactor: fix loop copy

- src/openvslam/CMakeLists.txt
Avoid clang warnings (see below) because `target_compile_options(${PROJECT_NAME} PRIVATE ${OpenMP_CXX_FLAGS})` is called even if USE_OPENMP=OFF.
```
clang: warning: argument unused during compilation: '-Xclang -fopenmp' [-Wunused-command-line-argument]
```
(I have not found if there is a good reason why this target_compile_options has been put outside the condition historically)
> chore: fix target_compile_options when USE_OPENMP=OFF

- CMakeLists.txt
Because pnp_solver.cc exceeds the max amount of sections in the .obj file
> Add /bigobj compile option for msvc

- src/stella_vslam/CMakeLists.txt
- src/stella_vslam/data/graph_node.cc
- src/stella_vslam/data/graph_node.h
- src/stella_vslam/data/landmark.h
- src/stella_vslam/mapping_module.cc
- src/stella_vslam/mapping_module.h
- src/stella_vslam/match/fuse.cc
- src/stella_vslam/match/robust.cc
- src/stella_vslam/match/robust.h
- src/stella_vslam/module/frame_tracker.cc
- src/stella_vslam/module/frame_tracker.h
- src/stella_vslam/module/initializer.cc
- src/stella_vslam/module/initializer.h
- src/stella_vslam/module/local_map_updater.h
- src/stella_vslam/module/loop_detector.cc
- src/stella_vslam/module/loop_detector.h
- src/stella_vslam/module/relocalizer.cc
- src/stella_vslam/module/relocalizer.h
- src/stella_vslam/tracking_module.cc
- src/stella_vslam/type.h
Fixes #293:
1. Pass the `use_fixed_seed` parameter from the Initializer to other relevant classes where possible, and introduce equivalent parameters in other YAML nodes (Relocalizer, LoopDetector).
2. Force the tracker to wait until the mapper has finished every time it passes a new keyframe across (this is a brute force solution that could probably be improved).
3. Sort landmarks/keyframes by ID rather than memory address where relevant.
Since (2) and (3) will potentially impact performance, the relevant code changes are disabled by default, enabled by running `cmake` with `-DDETERMINISTIC=ON`. The parameters in (1) are optional in any case, and default to false to preserve existing behaviour.
> Determinism fixes

- example/aist/equirectangular.yaml
- example/aist/fisyeye.yaml
- example/euroc/EuRoC_mono.yaml
- example/euroc/EuRoC_stereo.yaml
- example/kitti/KITTI_mono_00-02.yaml
- example/kitti/KITTI_mono_03.yaml
- example/kitti/KITTI_mono_04-12.yaml
- example/kitti/KITTI_stereo_00-02.yaml
- example/kitti/KITTI_stereo_03.yaml
- example/kitti/KITTI_stereo_04-12.yaml
- example/tum_rgbd/TUM_RGBD_mono_1.yaml
- example/tum_rgbd/TUM_RGBD_mono_2.yaml
- example/tum_rgbd/TUM_RGBD_mono_3.yaml
- example/tum_rgbd/TUM_RGBD_rgbd_1.yaml
- example/tum_rgbd/TUM_RGBD_rgbd_2.yaml
- example/tum_rgbd/TUM_RGBD_rgbd_3.yaml
- example/tum_vi/TUM_VI_mono.yaml
- example/tum_vi/TUM_VI_stereo.yaml
- src/stella_vslam/feature/CMakeLists.txt
- src/stella_vslam/feature/orb_extractor.cc
- src/stella_vslam/feature/orb_extractor.h
- src/stella_vslam/feature/orb_extractor_node.h
- src/stella_vslam/feature/orb_impl.cc
- src/stella_vslam/feature/orb_impl.h
- src/stella_vslam/system.cc
This change removes the resolution-dependent parameters `Preprocessing::max_num_keypoints` and `Preprocessing::ini_max_num_keypoints`, and adds a resolution-independent `Preprocessing::min_size` parameter.
> Modify distribute_keypoints_via_tree (Remove max_num_keypoints parameter)

- src/stella_vslam/data/landmark.cc
Obtain `min_valid_dist` based on current `max_valid_dist` instead of out-dated `max_valid_dist_`.
> Fix min_valid_dist

- src/stella_vslam/data/map_database.cc
When loading a map created with a monocular camera, stereo_x_right and depths had incorrect values.
> Skip loading of depth in monocular

- src/stella_vslam/mapping_module.cc
- src/stella_vslam/mapping_module.h
NOTE: update_new_keyframe is now always called. If it was not called, it could cause some problems.
> Update on mapping interruptions

- src/stella_vslam/data/map_database.cc
pass object by reference instead of copying value
> line 196 - pass by reference

- src/stella_vslam/io/map_database_io_sqlite3.cc
pass object by reference instead of copying value
> line 71 - pass by reference

- src/stella_vslam/data/graph_node.cc
- src/stella_vslam/data/graph_node.h
- src/stella_vslam/data/keyframe.cc
- src/stella_vslam/data/map_database.cc
- src/stella_vslam/data/map_database.h
- src/stella_vslam/global_optimization_module.cc
- src/stella_vslam/io/trajectory_io.cc
- src/stella_vslam/mapping_module.cc
- src/stella_vslam/module/initializer.cc
- src/stella_vslam/module/local_map_cleaner.cc
- src/stella_vslam/module/loop_bundle_adjuster.cc
- src/stella_vslam/module/loop_bundle_adjuster.h
- src/stella_vslam/optimize/global_bundle_adjuster.cc
- src/stella_vslam/optimize/global_bundle_adjuster.h
- src/stella_vslam/optimize/graph_optimizer.cc
- src/stella_vslam/optimize/graph_optimizer.h
- src/stella_vslam/optimize/local_bundle_adjuster.cc
- src/stella_vslam/publish/map_publisher.cc
- src/stella_vslam/tracking_module.cc
Reduced processing by origin_keyfrm_ and get_all_keyframes. This makes it easier to handle multiple non-overlapping maps. I will add the feature to load additional maps in a later pull request.
> Allow multiple root nodes

- .github/workflows/main.yml
- .gitmodules
- README.md
- example/CMakeLists.txt
- example/run_camera_slam.cc
- example/run_euroc_slam.cc
- example/run_image_slam.cc
- example/run_kitti_slam.cc
- example/run_tum_rgbd_slam.cc
- example/run_video_slam.cc
- scripts/ubuntu/README.md
- src/stella_vslam/data/map_database.cc
- src/stella_vslam/io/map_database_io_msgpack.cc
- src/stella_vslam/io/map_database_io_sqlite3.cc
- src/stella_vslam/system.cc
- src/stella_vslam/system.h
See
- https://github.com/stella-cv/stella_vslam/discussions/188
- https://github.com/stella-cv/stella_vslam/issues/223
- https://github.com/stella-cv/stella_vslam/pull/265
NOTE:
- Only the last map added is rendered.
- I did not add the features to translate, rotate, or scale the map. If needed, it would be preferable to create another executable that only performs the map conversion.
> Load non-overlapping maps

- src/stella_vslam/module/relocalizer.cc
The logic seems to be reversed. See https://github.com/stella-cv/stella_vslam/discussions/420.
> Fix refine_pose_by_local_map

- example/run_video_slam.cc
Added Visualize flag to enable and disable Pangolin visualization during SLAM execution (without altering the current features). Useful for headless systems (tested in a headless server).
> added visualize flag for pangolin

- src/stella_vslam/marker_detector/aruco.cc
- src/stella_vslam/marker_detector/aruco.h
Including <opencv2/aruco.hpp> in marker_detector/aruco.h causes a build failure for older OpenCV versions if `USE_ARUCO` is off due to the file not being present. Partial reversion of changes for #460 returns the header to aruco.cc.
Tested with OpenCV v4.5.5 only.
> Fix error when building without aruco (OpenCV < 4.7)

- .github/workflows/main.yml
- example/euroc/EuRoC_mono.yaml
- example/euroc/EuRoC_stereo.yaml
- example/run_camera_slam.cc
- example/run_euroc_slam.cc
- example/run_image_slam.cc
- example/run_kitti_slam.cc
- example/run_tum_rgbd_slam.cc
- example/run_video_slam.cc
- src/stella_vslam/data/map_database.cc
- src/stella_vslam/data/map_database.h
- src/stella_vslam/mapping_module.cc
- src/stella_vslam/mapping_module.h
- src/stella_vslam/module/local_map_updater.cc
- src/stella_vslam/module/local_map_updater.h
- src/stella_vslam/module/relocalizer.cc
- src/stella_vslam/optimize/local_bundle_adjuster_g2o.cc
- src/stella_vslam/optimize/local_bundle_adjuster_gtsam.cc
- src/stella_vslam/system.cc
- src/stella_vslam/system.h
- src/stella_vslam/tracking_module.cc
- src/stella_vslam/tracking_module.h
- If run with `--temporal-mapping`, keyframes loaded before running are prioritized for localization/localBA.
- If `erase_temporal_keyframes: true`, it will remove keyframes older than `num_temporal_keyframes`.
- If `enable_temporal_keyframe_only_tracking: true`, then tracking with only temporal keyframes will not be treated as Lost. If `--temporal-mapping` is not set, `enable_temporal_keyframe_only_tracking` will be ignored.
- If none of the above is specified, the behavior remains the same.
- Enabling all three of the above will run Visual SLAM with a limited number of keyframes
- If you set `--temporal-mapping` and `erase_temporal_keyframes: true`, load the map, and run it, you will get similar results to `--disable-mapping`, but the localization will be more stable.
> Temporal mapping based odometry

- src/stella_vslam/system.cc
This PR addresses this issue: https://github.com/stella-cv/stella_vslam/issues/531
The solution that the poster suggested worked properly. I looked through the mapper_module to be sure and indeed all the yaml params are accessed with default values (i.e. if they arent in the yaml node, a default value is assigned). 
To be certain, I also created a modified version of aist/equirectangular.yaml wherein I removed the `Mapping:` node entirely and from the yaml file and ran the aist_entrance_hall_1 equirectangular sequence. It worked as expected. here's the console output to verify this:
```
[2024-02-11 02:02:39.967] [I] config file loaded: /stella_vslam/example/aist/mod_equirect.yaml
--start-timestamp is not set. using system timestamp.
If --no-sleep is set without --start-timestamp, …
```
> [Bug fix] Make "Mapping" configuration field optional

- src/stella_vslam/optimize/pose_optimizer_factory.h
- src/stella_vslam/optimize/pose_optimizer_g2o.cc
- src/stella_vslam/optimize/pose_optimizer_g2o.h
Add parameters
- num_trials_robust
- num_trials
- num_each_iter
> Add parameters for pose_optimizer_g2o

- Dockerfile.iridescence
Hello,
I have made a change to the build directory for Iridescence. While other libraries are built in the `/tmp` directory, Iridescence is now built in the `/stella_vslam` directory.
Thank you.
> Change build directory based on other libraries

- .github/workflows/main.yml
- src/stella_vslam/global_optimization_module.cc
- src/stella_vslam/module/loop_bundle_adjuster.cc
- src/stella_vslam/module/loop_bundle_adjuster.h
> Add Options for GlobalOptimizer

- src/stella_vslam/publish/frame_publisher.cc
- src/stella_vslam/publish/frame_publisher.h
Landmarks are made from the size of undistorted keypoints, so they are exactly the same size.
If frame_publisher::update() is called in between get_keypoints() and get_landmarks() this assertion may not hold.
Add function which returns both in a pair without releasing the mutex lock
> [Issue #626] - Frame publisher function to get landmarks and keypoints with lock held

- Dockerfile.cuda
- src/stella_vslam/CMakeLists.txt
- src/stella_vslam/feature/orb_extractor.cc
- src/stella_vslam/feature/orb_extractor.h
- src/stella_vslam/system.cc
- test/stella_vslam/data/bow_vocabulary.cc
- test/stella_vslam/feature/orb_extractor.cc
Future work: rename names derived from ORB (e.g. orb_extractor)
> Use cuda-efficient-features (experimental)

- src/stella_vslam/global_optimization_module.cc
- src/stella_vslam/module/initializer.cc
- src/stella_vslam/module/initializer.h
- src/stella_vslam/module/loop_bundle_adjuster.cc
- src/stella_vslam/module/loop_bundle_adjuster.h
- src/stella_vslam/optimize/global_bundle_adjuster.cc
- src/stella_vslam/optimize/global_bundle_adjuster.h
- src/stella_vslam/optimize/local_bundle_adjuster_g2o.cc
- Add parameters about globalBA/g2o (verbose, gain_threshold)
- Default value of Initializer::num_ba_iterations is changed (20 -> 100)
- optimize_for_initialization automatically terminates optimization by gain_threshold
- some minor fixes
> Update initializer (Initialization with markers is now more stable)
