- Dockerfile.ros
ref.: https://github.com/xdspacelab/openvslam/pull/184
> Add Dockerfile for ROS

- Dockerfile.ros
> Fix Dockerfile.ros

- Dockerfile.ros
- Dockerfile.ros2
- scripts/docker/ci/Dockerfile.ros.ci
- scripts/docker/ci/Dockerfile.ros2.ci
- wercker.yml
CI for ROS now uses libraries installed by apt.
> Use libraries installed by apt

- README.md
- docs/installation.rst
Hi. As suggested, I'm separating the previous PR (docs from features). 
I put back the .gif, but it is now from a different source since the last one is not available anymore.
> [DOCS] updating readme file

- ros/1/src/openvslam/src/run_slam.cc
- ros/2/src/openvslam/src/run_slam.cc
- src/openvslam/data/bow_vocabulary.h
- src/openvslam/data/bow_vocabulary_fwd.h
- src/openvslam/system.cc
- src/openvslam/system.h
> Remove BoW header dependency

- docs/index.rst
- docs/installation.rst
- docs/overview.rst
- viewer/package.json
https://github.com/OpenVSLAM-Community/openvslam/issues/26
> change xdspacelab to openVSLAM community in docs

- src/openvslam/publish/frame_publisher.cc
> Fix missing header iomanip

- src/openvslam/camera/base.cc
- src/openvslam/camera/base.h
- src/openvslam/camera/equirectangular.cc
- src/openvslam/camera/equirectangular.h
- src/openvslam/camera/fisheye.cc
- src/openvslam/camera/fisheye.h
- src/openvslam/camera/perspective.cc
- src/openvslam/camera/perspective.h
- src/openvslam/config.cc
- src/openvslam/feature/orb_params.cc
- src/openvslam/feature/orb_params.h
- src/openvslam/system.cc
https://github.com/xdspacelab/openvslam/pull/452
> redirect << to spdlog

- src/openvslam/config.cc
- src/openvslam/config.h
- src/openvslam/tracking_module.cc
- src/openvslam/tracking_module.h
Related to https://github.com/xdspacelab/openvslam/pull/295, https://github.com/OpenVSLAM-Community/openvslam/issues/82
> Move tracking parameters to tracking_module

- src/openvslam/data/keyframe.cc
- src/openvslam/data/keyframe.h
- src/openvslam/mapping_module.cc
- src/openvslam/mapping_module.h
- src/openvslam/module/local_map_cleaner.cc
- src/openvslam/module/local_map_cleaner.h
- src/openvslam/system.cc
Removed is_monocular, which is equivalent to the information obtained from the current keyframe.
> Refactoring about is_monocular

- docs/parameters.rst
> Add description for focal_x_baseline for RGBD cameras

- src/openvslam/system.cc
- src/openvslam/system.h
- src/openvslam/tracking_module.cc
- src/openvslam/tracking_module.h
Use shared_ptr as the return value of `feed_*_frame` to represent an optional value
> Use shared_ptr as the return value of feed_*_frame

- src/openvslam/optimize/global_bundle_adjuster.cc
- src/openvslam/optimize/internal/landmark_vertex_container.h
- src/openvslam/optimize/internal/se3/shot_vertex_container.h
- src/openvslam/optimize/local_bundle_adjuster.cc
Added the ability to initialize vertices in any order.
> Refactoring vertex containers

- .github/workflows/main.yml
- scripts/docker/ci/Dockerfile.desktop.ci
- test/openvslam/data/bow_vocabulary.cc
Related to https://github.com/OpenVSLAM-Community/FBoW/issues/4#issuecomment-882585201
> Update FBoW and add test for BoW

- docs/docker.rst
- docs/example.rst
- example/CMakeLists.txt
- example/run_tum_rgbd_localization.cc
added new run_tum_rgbd_localization.cc and updated supporting documents to perform localization for RGBD setup.
> added new run_tum_rgbd_localization.cc and updated supporting documents

- docs/installation.rst
> Fix installation.rst (Add -DINSTALL_SOCKET_PUBLISHER=ON)

- docs/relocalization.rst
I've added an initial draft of Relocalization documentation which refer to #142 
Added `docs/relocalization.rst`
Which describes the rough flow for relocalization
> Added relocalization Documentation

- docs/relocalization.rst
- src/openvslam/module/relocalizer.cc
Added debug level log in relocalizer.cc #141
> Added Debug level log in Relocalization

- docs/parameters.rst
- src/openvslam/module/loop_detector.cc
> Add parameter LoopDetector::enabled

- src/openvslam/data/map_database.cc
- src/openvslam/data/map_database.h
- src/openvslam/system.cc
- src/openvslam/system.h
- src/openvslam/tracking_module.cc
- src/openvslam/tracking_module.h
Related to https://github.com/OpenVSLAM-Community/openvslam_ros/issues/11.
> Relocalize by 2d pose request

- src/openvslam/initialize/bearing_vector.cc
Fix use_fixed_seed for equirectangular camera
https://github.com/OpenVSLAM-Community/openvslam/pull/78
> fix: use_fixed_seed for equirectangular camera

- src/openvslam/data/landmark.cc
- src/openvslam/tracking_module.cc
> Fix landmark.cc (empty observations_)

- Dockerfile.desktop
- Dockerfile.socket
- cmake/FindSQLite3.cmake
- package.xml
- scripts/docker/ci/Dockerfile.desktop.ci
- src/stella_vslam/CMakeLists.txt
- src/stella_vslam/data/camera_database.cc
- src/stella_vslam/data/camera_database.h
- src/stella_vslam/data/landmark.cc
- src/stella_vslam/data/landmark.h
- src/stella_vslam/data/map_database.cc
- src/stella_vslam/data/map_database.h
- src/stella_vslam/io/CMakeLists.txt
- src/stella_vslam/io/map_database_io_base.h
- src/stella_vslam/io/map_database_io_msgpack.cc
- src/stella_vslam/io/map_database_io_msgpack.h
- src/stella_vslam/io/map_database_io_sqlite3.cc
- src/stella_vslam/io/map_database_io_sqlite3.h
- src/stella_vslam/system.cc
- src/stella_vslam/system.h
> Use sqlite

- src/stella_vslam/data/graph_node.cc
- src/stella_vslam/data/graph_node.h
- src/stella_vslam/data/landmark.h
- src/stella_vslam/mapping_module.cc
- src/stella_vslam/mapping_module.h
- src/stella_vslam/match/fuse.cc
- src/stella_vslam/module/local_map_updater.h
- src/stella_vslam/type.h
> Fix readability

- src/stella_vslam/marker_model/CMakeLists.txt
Seems like variable name was not updated in this CMakeList.txt
> Update CMakeLists.txt for marker_model

- src/stella_vslam/camera/base.cc
- src/stella_vslam/data/map_database.cc
Relate to https://github.com/stella-cv/stella_vslam/issues/308
> Fix loading of bearings

- src/stella_vslam/optimize/global_bundle_adjuster.cc
- src/stella_vslam/optimize/graph_optimizer.cc
- src/stella_vslam/optimize/local_bundle_adjuster.cc
- src/stella_vslam/optimize/pose_optimizer.cc
Relate to https://github.com/stella-cv/stella_vslam/issues/345.
> Release terminate action

- src/stella_vslam/tracking_module.cc
> Fix search_local_landmarks

- src/stella_vslam/config.cc
- src/stella_vslam/data/orb_params_database.cc
> Add log for orb_params

- example/run_camera_slam.cc
- example/run_image_slam.cc
- example/run_video_slam.cc
- example/util/image_util.cc
- example/util/image_util.h
> Use unix time in run_camera_slam, run_image_slam, run_video_slam

- src/stella_vslam/data/common.h
- src/stella_vslam/match/projection.h
- src/stella_vslam/match/robust.h
- src/stella_vslam/optimize/pose_optimizer.h
> Fix forward declaration

- src/stella_vslam/config.cc
- src/stella_vslam/config.h
- src/stella_vslam/data/camera_database.cc
- src/stella_vslam/data/camera_database.h
- src/stella_vslam/data/map_database.cc
- src/stella_vslam/data/orb_params_database.cc
- src/stella_vslam/data/orb_params_database.h
- src/stella_vslam/feature/orb_params.cc
- src/stella_vslam/system.cc
NOTE: The map format has not changed with this change.
> Refactor parameter database

- src/socket_publisher/data_serializer.cc
pass object by reference instead of copying value
> lines 93, 136, 146, 169 - pass by reference

- src/stella_vslam/match/stereo.cc
> Updated variable initialization

- src/stella_vslam/initialize/base.cc
- src/stella_vslam/initialize/base.h
- src/stella_vslam/initialize/bearing_vector.cc
- src/stella_vslam/initialize/bearing_vector.h
- src/stella_vslam/initialize/perspective.cc
- src/stella_vslam/initialize/perspective.h
- src/stella_vslam/module/initializer.cc
- src/stella_vslam/module/initializer.h
ref. https://github.com/stella-cv/stella_vslam/pull/398
> Fix triangulation in initializer

- src/stella_vslam/data/graph_node.cc
> Rename keyfrm_and_num_shared_lms to keyfrm_to_num_shared_lms

- .github/workflows/main.yml
- example/aist/equirectangular.yaml
- example/aist/fisheye.yaml
- example/euroc/EuRoC_mono.yaml
- example/euroc/EuRoC_stereo.yaml
- src/stella_vslam/data/keyframe.cc
- src/stella_vslam/data/landmark.cc
- src/stella_vslam/data/map_database.cc
> Fix bug in saving with sqlite3

- Dockerfile.desktop
- Dockerfile.socket
- docker/gtsam/pangolin/Dockerfile
- docker/gtsam/socket/Dockerfile
- scripts/docker/ci/Dockerfile.desktop.ci
- src/stella_vslam/marker_detector/aruco.cc
- src/stella_vslam/marker_detector/aruco.h
> Support OpenCV 4.7

- example/run_image_slam.cc
> Abbreviation of --img-dir to -d

- example/run_camera_slam.cc
- example/run_euroc_slam.cc
- example/run_image_slam.cc
- example/run_kitti_slam.cc
- example/run_loop_closure.cc
- example/run_tum_rgbd_slam.cc
- example/run_video_slam.cc
- src/stella_vslam/io/map_database_io_base.h
- src/stella_vslam/io/map_database_io_msgpack.cc
- src/stella_vslam/io/map_database_io_msgpack.h
- src/stella_vslam/io/map_database_io_sqlite3.cc
- src/stella_vslam/io/map_database_io_sqlite3.h
- src/stella_vslam/system.cc
- src/stella_vslam/system.h
- src/stella_vslam/util/sqlite3.cc
Close #467
ref. https://github.com/stella-cv/stella_vslam/issues/449, https://github.com/stella-cv/stella_vslam/pull/451
> Fix create_insert_stmt

- src/stella_vslam/tracking_module.cc
- src/stella_vslam/tracking_module.h
> Add parameter init_retry_threshold_time

- example/euroc/EuRoC_mono.yaml
- example/euroc/EuRoC_stereo.yaml
- src/stella_vslam/mapping_module.cc
- src/stella_vslam/mapping_module.h
- src/stella_vslam/module/keyframe_inserter.cc
- src/stella_vslam/module/keyframe_inserter.h
- src/stella_vslam/tracking_module.cc
- src/stella_vslam/tracking_module.h
and
- Add parameter KeyframeInserter::wait_for_local_bundle_adjustment
- Move keyframe insertion from tracking_module::track
- New async_add_keyframe allows you to wait for keyframes added to mapping_module to be processed.
> [refactoring] Remove mapping_module::is_idle_

- Dockerfile.iridescence
Created a new viewer using https://github.com/koide3/iridescence.
> Add Dockerfile.iridescence

- CMakeLists.txt
- src/stella_vslam/CMakeLists.txt
- src/stella_vslam/marker_detector/aruco.cc
- src/stella_vslam/marker_detector/aruco.h
> Fix aruco for OpenCV>=4.7
